### ISSUE TITLE
sqlite文件不存在,无法生成

### ISSUE THREAD

**Issue by dfmjndm** [A-kirami/GroupWordCloudGenerator#3]
[2022-07-03 23:58:44,066 nonebot] ERROR: Failed to import and load "hoshino.modules.GroupWordCloudGenerator.Sqlite3Manager", error: unable to open database file
[2022-07-03 23:58:44,066 nonebot] ERROR: unable to open database file
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/nonebot/plugin.py", line 419, in _load_plugin
    module = importlib.import_module(module_path)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/hobot/hoshino/modules/GroupWordCloudGenerator/__init__.py", line 15, in <module>
    from .Sqlite3Manager import execute_sql
  File "/hobot/hoshino/modules/GroupWordCloudGenerator/Sqlite3Manager.py", line 65, in <module>
    manager = Sqlite3Manager()
  File "/hobot/hoshino/modules/GroupWordCloudGenerator/Sqlite3Manager.py", line 19, in __init__
    self.__conn = sqlite3.connect(self.path + './hoshino/modules/GroupWordCloudGenerator/chatRecord.db')
sqlite3.OperationalError: unable to open database file

**Comment by dfmjndm** [comment]
手动建了一个，644权限，还是不行
![image](https://user-images.githubusercontent.com/57401901/177048924-0c7145a2-0f74-4c5d-9d8c-e6571d450602.png)

**Comment by dfmjndm** [comment]
修改为绝对路径，数据库可以用了
出现了新的问题
[2022-07-04 00:41:31,396 nonebot] ERROR: Failed to import and load "hoshino.modules.GroupWordCloudGenerator.Sqlite3Manager", error: [Errno 2] No such file or directory: '/usr/local/lib/python3.9/site-packages/pkuseg-0.0.25-py3.9-linux-x86_64.egg/pkuseg/models/default/unigram_word.txt'
[2022-07-04 00:41:31,396 nonebot] ERROR: [Errno 2] No such file or directory: '/usr/local/lib/python3.9/site-packages/pkuseg-0.0.25-py3.9-linux-x86_64.egg/pkuseg/models/default/unigram_word.txt'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/nonebot/plugin.py", line 419, in _load_plugin
    module = importlib.import_module(module_path)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/hobot/hoshino/modules/GroupWordCloudGenerator/__init__.py", line 33, in <module>
    seg = pkuseg.pkuseg()
  File "/usr/local/lib/python3.9/site-packages/pkuseg-0.0.25-py3.9-linux-x86_64.egg/pkuseg/__init__.py", line 241, in __init__
    self.feature_extractor = FeatureExtractor.load()
  File "pkuseg/feature_extractor.pyx", line 625, in pkuseg.feature_extractor.FeatureExtractor.load
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.9/site-packages/pkuseg-0.0.25-py3.9-linux-x86_64.egg/pkuseg/models/default/unigram_word.txt'

**Comment by dfmjndm** [comment]
已解决，手动编译了个3.9的包，pkuseg开发者估计都忘记有这个项目了
